@username = g00glen00b
@password = my-not-so-secret-password
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOm51bGwsInN1YiI6IjVmYzUyMTliLWZjYWYtNDI2MS1iYWU4LWRjYTZjOWRjZWQxNiIsImV4cCI6MTc1ODA2MDEyMywidW5tIjoiZzAwZ2xlbjAwYiIsImRubSI6IkRpbWl0cmkiLCJpYXQiOjE3NTgwNTY1MjN9.idCfZDljAOwjek7MlwpaBn-7KMV_39873rmSZBNaFAc
@imageId = 23bb79f5-bc28-4044-ad2a-d8baa87acc3f
@page = 1
@pagesize = 10

GET http://localhost:8080/api/recipe?page={{page}}&size={{pagesize}}&sort=title,asc

###

POST http://localhost:8080/api/chef
Content-Type: application/json

{
  "username": "{{username}}",
  "displayname": "Dimitri",
  "password": "{{password}}"
}

###

GET http://localhost:8080/api/chef/token
Authorization: Basic {{username}} {{password}}

###

GET http://localhost:8080/api/chef
Authorization: Bearer {{token}}

###

POST http://localhost:8080/api/recipe
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "title": "S'mores",
  "description": "Heat marshmallow over an open flame until golden brown. Sandwich between two graham crackers with a piece of chocolate."
}

--boundary
Content-Disposition: form-data; name="image"; filename="image1.jpg"
Content-Type: image/jpeg

< test-data/image1.jpg

--boundary
Content-Disposition: form-data; name="image"; filename="image2.jpg"
Content-Type: image/jpeg

< test-data/image2.jpg
--boundary--

###

GET http://localhost:8080/api/recipe/image/{{imageId}}